[package]
name = "integration_tests"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
doctest = false

[dependencies]

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
sentinel_types = { path = "../sentinel_types", features = ["testutils"] }
controller = { path = "../controller" }
governance_module = { path = "../governance_module" }
risk_vault = { path = "../risk_vault" }
oracle_aggregator = { path = "../oracle_aggregator" }
flight_pool_manager = { path = "../flight_pool_manager" }

[lints]
workspace = true
