import { useTheme } from "./providers/ThemeProvider"

/**
 * Theme-driven wording. Fun keeps the arcade / prediction-market voice;
 * Serious speaks plain parametric-insurance. Both objects MUST have the
 * same shape — `Copy` is derived from the fun map so TypeScript flags any
 * key that serious forgets (or vice-versa).
 *
 * Usage:  const t = useCopy();  t.nav.markets
 * For interpolated strings, values are functions: t.markets.insureBtn(10)
 */
const fun = {
	nav: {
		markets: "PREDICT",
		globe: "LIVE",
		policies: "POLICIES",
		earn: "EARN",
		settings: "SETTINGS",
		information: "INFORMATION",
		keepers: "KEEPERS",
		seatbelters: "SEATBELTERS",
		docs: "DOCS",
	},
	wallet: {
		connect: "INSERT COIN — CONNECT",
		menuAria: "Wallet menu",
		copyAddress: "COPY ADDRESS",
		disconnect: "DISCONNECT",
		copied: "Address copied to clipboard",
		copyFailed: "Copy failed — try again",
		connected: (addr: string) => `WALLET CONNECTED — ${addr}`,
		disconnected: (addr: string) => `WALLET DISCONNECTED — ${addr}`,
		mismatchBanner: (net: string) =>
			`Your wallet is on a different network than this app (${net}). Switch your wallet to ${net} before signing.`,
	},
	brand: {
		name: "FLIGHTS.FUN",
		tagline: "PARAMETRIC FLIGHT INSURANCE. PLAYED LIKE A MARKET.",
	},
	markets: {
		heroLine1: "INSURE YOUR FLIGHT.",
		heroLine2: "GET PAID IF IT'S LATE.",
		heroSub:
			"Buying insurance here IS predicting your flight lands late. Stake a fixed premium; if the flight is delayed past the threshold, the payout is yours automatically.",
		heroCtaBoard: "TO THE BOARD",
		boardTitle: "DEPARTURES — OPEN MARKETS",
		boardHint: "PAY PREMIUM → PAID IF DELAYED",
		colStake: "PREMIUM → PAYOUT",
		searchPlaceholder: "Flight or airport… (AA100, JFK)",
		searchAria: "Search flights by number or airport code",
		flightCount: (n: number) => `${n} FLIGHT${n === 1 ? "" : "S"}`,
		scanning: "SCANNING CHAIN",
		colFlight: "FLIGHT",
		colRoute: "ROUTE",
		colTrigger: "TRIGGER",
		colStatus: "STATUS",
		triggerCell: (h: number) => `>${h}H LATE`,
		triggerTitle: (h: number) =>
			`PAYS PAST A ${h}H DELAY — OR CANCELLATION`,
		statusScanning: "◌ SCANNING",
		statusDemo: "◌ DEMO",
		statusRecent: "RECENT",
		statusBoarding: "● BOARDING",
		noMatch: (q: string) => `NO FLIGHTS MATCH “${q}”`,
		noMatchHint: "Try a flight number or an airport code.",
		insureBtn: (odds: number) => `INSURE ✈ ${odds}X`,
		insureTitle: (odds: number) =>
			`BUY COVER — PAYS ${odds}X THE PREMIUM IF THIS FLIGHT IS DELAYED`,
		stakeTitle: (premium: string, payout: string) =>
			`PAY ${premium} USDC NOW — COLLECT ${payout} USDC IF DELAYED`,
		yieldBtn: "EARN YIELD",
		yieldTitle: "Take the other side — underwrite flights from the pool",
		pageLabel: (page: number, total: number, count: number) =>
			`PAGE ${page} OF ${total} · ${count} FLIGHT${count === 1 ? "" : "S"}`,
		pagePrev: "◀ PREV",
		pageNext: "NEXT ▶",
		pageOf: (page: number, total: number) => `PAGE ${page}/${total}`,
		perPage: "PER PAGE",
		perPageAria: "Flights per page",
		sortAria: (col: string) => `Sort by ${col}`,
		flightLinkTitle: (id: string) =>
			`TRACK ${id} ON FLIGHTRADAR24 ↗ (opens in a new tab)`,
		yieldExplain:
			"takes the other side: it routes you to the underwriting pool, where on-time premiums become your yield.",
		yieldExplainLead: "EARN YIELD",
		demoNote:
			"DEMO rows — no live markets whitelisted on-chain right now.",
	},
	statsTicker: {
		tag: "STATS",
		tvl: "TVL",
		free: "FREE CAPITAL",
		premiums: "PREMIUMS",
		policiesSold: "POLICIES SOLD",
		openMarkets: "OPEN MARKETS",
		insurancesPaid: "INSURANCES PAID",
		delayed: "DELAYED",
		cancelled: "CANCELLED",
		paidOut: "TOTAL PAID OUT",
		unavailable: "Not available right now",
	},
	slip: {
		title: "INSURANCE SLIP",
		eyebrow: "BOARDING PASS",
		closeAria: "Close insurance slip",
		oddsLabel: (odds: string) => `DELAYED PAYS ${odds}`,
		triggerLabel: "DELAY TRIGGER",
		dateLabel: "FLIGHT DATE (UTC)",
		datePlaceholder: "PICK A DAY ▾",
		departsLabel: "DEPARTS",
		departsApprox: (date: string, hm: string, iata: string) =>
			`${date} · ≈${hm} ${iata}`,
		utcShiftNote: (date: string) =>
			`BOARD DATES ARE UTC — THIS COVERS THE FLIGHT YOUR BOARDING PASS CALLS ${date}.`,
		calPrevAria: "Previous month",
		calNextAria: "Next month",
		calCloseAria: "Close calendar",
		premiumLabel: "PREMIUM (FIXED)",
		walletLabel: "YOUR USDC",
		insufficientPrompt:
			"Not enough USDC for this premium — top up your wallet first.",
		payoutLabel: "PAYOUT IF DELAYED",
		cta: (amt: string) => `BUY COVER ✈ ${amt} USDC`,
		pickDateHint: "Pick a flight date first.",
		connectPrompt: "Connect your wallet to buy this cover.",
		blockedPrompt: "Cover is currently limited to approved buyers.",
		unavailablePrompt: "This route is no longer available.",
		fineprint:
			"Buying cover IS predicting your flight lands late: the premium is your stake on DELAYED. An oracle settles the flight on-chain after it lands. No claims forms.",
	},
	// First-visit agreement gate. Deliberately professional in BOTH themes —
	// eligibility and risk notices don't get the arcade voice.
	agreement: {
		eyebrow: "NOTICE",
		title: "BEFORE YOU USE THIS DAPP",
		intro: "Please read these and confirm your eligibility before using the dapp. The full documents:",
		privacyLink: "Privacy Policy",
		termsLink: "Terms of Service",
		disclaimersLink: "Disclaimers",
		sections: [
			{
				heading: "THE SERVICE",
				body: "This application is an interface to open-source parametric flight-delay insurance contracts deployed on the Stellar network. The interface operator does not custody user funds, does not act as your counterparty, and does not execute transactions on your behalf; every transaction is built and signed by your own wallet.",
			},
			{
				heading: "ELIGIBILITY",
				body: "You may not use this application if you are a resident of, or accessing it from, a prohibited or sanctioned jurisdiction, or if you are otherwise barred from using it under applicable law. It is your responsibility to confirm that using it is lawful where you are.",
			},
			{
				heading: "RISK DISCLOSURE",
				body: "Using on-chain protocols involves substantial risk of loss, up to the total loss of any funds you commit. Smart contracts may contain bugs, flight data and oracles can be late or wrong, and confirmed transactions cannot be reversed. You alone are responsible for your decisions.",
			},
			{
				heading: "NO ADVICE",
				body: "Nothing in this application constitutes financial, investment, legal, tax, accounting, or insurance advice.",
			},
			{
				heading: "CHANGES",
				body: "These terms may change as the protocol evolves; continued use after a change constitutes acceptance of the updated terms.",
			},
		],
		representation:
			"By pressing “Got it”, I confirm that I have read the notices above, that I am not a resident of, and am not accessing this application from, a prohibited or sanctioned jurisdiction, and that I am legally permitted to use it.",
		draftNote:
			"This summary is provided for convenience and is not the final legal language. Questions or concerns? Open an issue on",
		issuesLink: "GitHub",
		accept: "GOT IT",
	},
	seatbelters: {
		title: "SEATBELTERS",
		sub: "THOSE WHO KNOW HOW TO PLAY IT SAFE.",
		windowLabel: "WINDOW",
		windowAria: "Leaderboard time window",
		window24h: "24H",
		window7d: "7D",
		window30d: "30D",
		windowAll: "ALL TIME",
		colRank: "SEAT",
		colWho: "WHO",
		colPolicies: "POLICIES",
		colPremium: "STAKED",
		colWins: "WINS",
		colPnl: "P&L",
		rankTitle: "Seats are ranked by net P&L — payouts collected minus premiums paid.",
		winsTitle: "Covered flights that settled delayed or cancelled — the ones that paid.",
		pnlTitle: "Payouts collected minus premiums paid. Seats are ranked by this.",
		loading: "FASTENING",
		loadError: "BOARD UNAVAILABLE — TRY AGAIN IN A MOMENT.",
		empty: "NO SEATBELTERS YET. BUCKLE UP FIRST, BRAG FOREVER.",
		emptyWindow: "QUIET SKIES — NO COVER BOUGHT IN THIS WINDOW.",
		emptyCta: "TO THE BOARD",
		seatsOpen: (n: number) =>
			`${n} SEAT${n === 1 ? "" : "S"} STILL OPEN ON THIS LIST.`,
		explorerTitle: (label: string) => `View account on ${label} ↗`,
		youTitle: "YOUR SEAT",
		you: "YOU",
		youConnect: "INSERT COIN — CONNECT WALLET TO FIND YOUR SEAT.",
		youOffBoard: "NO COVER BOUGHT IN THIS WINDOW → NO SEAT YET.",
		youError: "YOUR SEAT IS UNAVAILABLE RIGHT NOW.",
		fineprint:
			"TESTNET NUMBERS — TEST USDC IS FREE, GLORY ISN'T. Seats rank by net P&L over policies seen by the chain-event mirror.",
	},
	house: {
		heroLine1: "EARN YIELD.",
		heroLine2: "BE THE UNDERWRITER.",
		sub: "Every on-time flight pays the underwriting pool. Deposit USDC, take a share of every premium, and absorb the payouts when flights run late.",
		statTvl: "POOL (TVL)",
		statBacking: "BACKING POLICIES",
		statFree: "FREE CAPITAL",
		statApr: "REALIZED APR (90D)",
		aprHover: (apy: string, days: number) =>
			`${apy}% APY (compounded) · measured over ${days}d of recorded vault history`,
		aprInfo:
			"WHAT THE POOL ACTUALLY EARNED, ANNUALIZED — NOT A PROMISED RATE. Underwriters take the premium on every policy and fund the payout on every delayed or cancelled flight; the net lands in the share price, so the share price is the only input. We read it at the two ends of a 90-day window and annualize: APR = (end ÷ start − 1) × 365 ÷ days. Hover the number for the APY, which compounds the same move instead: APY = (end ÷ start) ^ (365 ÷ days) − 1. That compounding is the ONLY difference between them — identical data, so APY always reads higher, and wildly higher over a short window. The window is fixed at 90 days on purpose: annualizing a few days turns one settlement into a headline (this vault printed +357% APY, then a dash, then −55% APY inside four days while its share price moved a total of +1.0%). It is backward-looking either way, and a dash means too little recorded history to measure. The window only reaches back as far as the vault's recorded history goes — hover shows how many days were actually measured.",
		deposit: "DEPOSIT",
		depositAmount: "AMOUNT (USDC)",
		walletBalance: "Wallet:",
		walletHint: "· mint test USDC from the top bar.",
		bridgeLink: "bridge USDC (for mainnet)",
		depositCta: "DEPOSIT — EARN YIELD",
		depositQueueHint:
			"Deposits queue for a ~6-hour safety delay, then shares mint to your wallet automatically — at the share price when processed, not when queued.",
		depositQueued: (amt: string) => `${amt} USDC queued`,
		maxBtn: "MAX",
		insufficientBalance: "That's more USDC than your wallet holds.",
		connectWallet: "CONNECT WALLET",
		position: "YOUR POSITION",
		poolShares: "POOL SHARES",
		currentValue: "CURRENT VALUE",
		premiumsEarned: "PREMIUMS EARNED (ALL TIME)",
		cashOut: "CASH OUT",
		cashOutAmount: "AMOUNT (SHARES)",
		insufficient: "That's more shares than you hold.",
		queueCta: "QUEUE CASH-OUT",
		queueHint:
			"Cash-outs unlock after a ~6-hour safety delay, then pay out as the vault frees capital — collect below when ready.",
		withdrawPreview: (amt: string) => `≈ ${amt} USDC at the current share price`,
		yourQueue: "YOUR QUEUE",
		queueEmpty: "NO QUEUED CASH-OUTS",
		queuePosition: (n: number) => `#${n} in line`,
		queueShares: (amt: string) => `${amt} shares`,
		queueEta: (when: string) => `UNLOCKS IN ~${when}`,
		queueReady: "READY — AWAITING NEXT POOL PASS",
		cancel: "CANCEL",
		readyToCollect: "READY TO COLLECT",
		collectCta: "COLLECT ★",
		nothingToCollect: "NOTHING TO COLLECT YET",
		fineprint:
			"The underwriting pool is a Soroban vault: deposits mint shares, premiums accrue to the share price, and payouts on delayed flights are absorbed by the vault. Deposits and cash-outs are both processed after a ~6-hour safety delay, at the share price current at processing time. Underwriting carries risk.",
		calcCta: "HOW MUCH CAN YOU EARN? → RUN THE NUMBERS",
		calcCtaHead: "HOW MUCH CAN YOU EARN?",
		calcCtaTail: "RUN THE NUMBERS ▶",
		utilWarn:
			"POOL FULLY UTILIZED — CASH-OUTS QUEUE UNTIL CAPITAL FREES UP.",
		queueRail: "THE CASH-OUT LINE",
		queueRailEmpty: "LINE'S EMPTY — NO CASH-OUTS QUEUED.",
		queueMine: "YOU",
		sharePriceTitle: "SHARE PRICE",
		sharePriceSub: (n: number) => `LAST ${n} DAYS`,
		realizedYield: (period: string, days: number, apr: string, apy: string) =>
			`REALIZED ${period}% OVER ${days}D ≈ ${apr}% APR · ${apy}% APY`,
		illustrative: "ILLUSTRATIVE",
		statsUnavailable:
			"SOME POOL NUMBERS DIDN'T LOAD — RETRYING AUTOMATICALLY.",
		sparkTvl: "TVL TREND",
		sparkApy: "APY TREND",
	},
	policies: {
		title: "MY POLICIES",
		connectPrompt: "INSERT COIN — CONNECT WALLET (TOP RIGHT)",
		connectSub:
			"Connect your wallet to see your active cover, payouts to claim, and settled slips.",
		intro:
			"Your slips: active cover in the air, payouts to claim, and settled history.",
		loading: "PULLING YOUR SLIPS",
		loadError: "COULDN'T LOAD YOUR SLIPS — THE CHAIN DIDN'T ANSWER.",
		loadErrorSub:
			"Your policies are safe on-chain; this page just couldn't read them right now.",
		retry: "RETRY",
		liveScheduled: "SCHEDULED",
		liveInAir: "IN AIR",
		liveLanded: "LANDED",
		liveCancelled: "CANCELLED",
		liveDelayedSettling: "DELAYED — SETTLING",
		liveOnTimeSettling: "ON TIME — SETTLING",
		outcomeOnTime: "ON TIME — NO PAYOUT",
		outcomeDelayedPays: "DELAYED — PAYS OUT",
		outcomeCancelledPays: "CANCELLED — PAYS OUT",
		outcomeDelayedPaid: "DELAYED — PAID",
		outcomeCancelledPaid: "CANCELLED — PAID",
		outcomeDelayedExpired: "DELAYED — EXPIRED",
		outcomeCancelledExpired: "CANCELLED — EXPIRED",
		empty: "NO POLICIES YET",
		emptyCta: "HIT THE BOARD ✈",
		total: (n: number) => `${n} SLIP${n === 1 ? "" : "S"} ON RECORD`,
		active: "ACTIVE",
		activeSub: "Live cover. We're tracking these flights.",
		claim: "★ READY TO CLAIM — GRAB YOUR PAYOUT",
		claimSub: "Delayed or cancelled. Claim before the window shuts.",
		claimWin: "DELAYED — YOU WIN!",
		claimBtn: "CLAIM PAYOUT ★",
		claiming: "CLAIMING…",
		payoutLabel: "PAYOUT",
		history: "HISTORY — SETTLED",
		historySub: "Closed slips. Here's why each is done.",
		historyFilterLabel: "SHOW",
		historyFilterAria: "Hide settled policies older than",
		historyFilterAll: "ALL",
		historyFilterDays: (d: number) => `LAST ${d} DAYS`,
		historyStatusLabel: "STATUS",
		historyStatusAria: "Show only settled policies with this status",
		historyHidden: (n: number) => `${n} HIDDEN BY FILTERS`,
		badgeTracking: "TRACKING",
		badgeOnTime: "ON TIME",
		badgeClaimable: "PAYS OUT",
		badgePaid: "PAID OUT",
		badgeExpired: "WINDOW SHUT",
		reasonPaid: "Paid out — payout claimed.",
		reasonOnTime: "On time — no payout.",
		reasonExpired: "Claim window expired — unclaimed.",
		reasonDelayedPaid: "Delayed — paid out.",
		reasonCancelledPaid: "Cancelled — paid out.",
		claimWindow: (d: string) => `CLAIM BY ${d}`,
		expiresIn: (left: string) => `EXPIRES IN ${left}`,
		expiresNow: "WINDOW CLOSING — CLAIM NOW",
		remindBtn: "🔔 REMIND ME",
		remindBtnTitle:
			"Get a browser notification when a payout is close to expiring",
		remindOn:
			"Reminders on — you'll get a heads-up when a payout nears expiry.",
		notifTitle: (amt: string) => `${amt} USDC payout waiting`,
		notifBody: (flight: string, left: string) =>
			`${flight}: claim before the window shuts — ${left} left.`,
		depTime: (hm: string) => `DEP ${hm}`,
	},
	// OS notification strings + the post-first-transaction permission card.
	// Notification text stays sentence case in BOTH themes — it renders in
	// the OS shell, not the app.
	alerts: {
		promptTitle: "STAY IN THE LOOP?",
		promptBody:
			"Get a browser alert when your flight is delayed, a payout is ready, or your vault deposit is processed. Works while a tab with this app is open.",
		promptEnable: "ENABLE ALERTS",
		promptDismiss: "NOT NOW",
		promptNever: "NEVER",
		enabledToast:
			"Alerts on — you'll get a heads-up when something needs you.",
		delayed: (f: string) => `${f} is delayed`,
		delayedBody: "Your covered flight hit the threshold — a payout is on the way.",
		cancelledFlight: (f: string) => `${f} was cancelled`,
		cancelledBody: "Your covered flight was cancelled — a payout is on the way.",
		settledOnTime: (f: string) => `${f} landed on time`,
		settledOnTimeBody: "Policy settled — no payout this trip.",
		payoutReady: (amt: string) => `Payout ready: ${amt} USDC`,
		payoutReadyBody: (f: string) =>
			`${f} settled in your favor. Claim before the window closes.`,
		depositProcessed: "Vault deposit processed",
		depositProcessedBody: "Your shares are minted and earning.",
		withdrawalProcessed: "Vault withdrawal processed",
		withdrawalProcessedBody: "Your USDC is ready to collect on the Earn page.",
	},
	policyDetail: {
		eyebrow: "POLICY RECORD",
		detailsLink: "DETAILS ▸",
		back: "◄ MY POLICIES",
		loading: "PULLING THE RECORD",
		loadError: "COULDN'T READ THE CHAIN.",
		loadErrorSub:
			"The record is safe on-chain; this page just couldn't read it right now.",
		retry: "RETRY",
		notFound: "NO RECORD ON THIS FLIGHT",
		notFoundSub:
			"Nothing on-chain for this flight and date. Check the link, or hit the board.",
		notFoundCta: "TO THE BOARD ✈",
		dateLabel: "FLIGHT DATE (UTC)",
		premiumLabel: "PREMIUM",
		payoutLabel: "PAYOUT IF DELAYED",
		triggerLabel: (h: number) => `TRIGGER: >${h}H LATE — OR CANCELLED`,
		buyers: (n: number) => `${n} SLIP${n === 1 ? "" : "S"} SOLD`,
		claimedOf: (c: number, n: number) => `${c}/${n} CLAIMED`,
		viewingAs: (addr: string) => `SLIP HELD BY ${addr}`,
		noPolicyForWallet:
			"This wallet holds no slip on this flight — showing the market record.",
		timelineTitle: "THE PAPER TRAIL",
		timelineSub:
			"Every step below is a public on-chain fact you can verify independently.",
		stepSaleTitle: "SALE WINDOW",
		stepSaleOpen: (d: string) => `Open — cover on sale until ${d}.`,
		stepSaleDone:
			"The flight was verified against the live schedule, then sales shut before departure.",
		stepSaleNone: "No sale window on record for this flight and date.",
		stepBuyTitle: "COVER BOUGHT",
		stepBuyKnown: (premium: string) =>
			`${premium} USDC premium staked. The slip lives on-chain.`,
		stepBuyMarket: (n: number) =>
			`${n} traveler${n === 1 ? "" : "s"} bought this cover.`,
		stepBuyNone: "No slips sold on this flight.",
		boughtAt: (when: string) => `BOUGHT ${when}`,
		stepEtaTitle: "SCHEDULE ATTESTED",
		stepEtaDone: (when: string) =>
			`The oracle wrote the published timetable: scheduled arrival ${when}. Every payout decision is measured from this instant.`,
		stepEtaPending:
			"The oracle writes the published timetable when tracking starts.",
		stepOutcomeTitle: "FLIGHT OUTCOME",
		stepOutcomeLanded: (when: string) => `Landed ${when}.`,
		stepOutcomeLate: (dur: string) =>
			`That's ${dur} past the scheduled arrival.`,
		stepOutcomeNotLate: "At (or before) the scheduled arrival.",
		stepOutcomeCancelled:
			"Cancelled — corroborated by the oracle before being written on-chain.",
		stepOutcomePending: "Still to come — the flight hasn't landed yet.",
		stepSettleTitle: "SETTLED ON-CHAIN",
		settleMathLate: (late: string, h: number) =>
			`${late} late vs the ${h}h trigger → DELAYED. THE CONTRACT PAYS.`,
		settleMathOnTime: (late: string, h: number) =>
			`${late} late vs the ${h}h trigger → ON TIME. No payout.`,
		settleCancelled: "Cancelled → THE CONTRACT PAYS the full payout.",
		stepSettlePending:
			"Waiting on the keeper sweep — settlement is automatic, no claim forms.",
		settledAt: (when: string) => `SETTLED ${when}`,
		stepClaimTitle: "PAYOUT",
		claimPaid: (amt: string) => `${amt} USDC claimed. Money in the wallet.`,
		claimReady: (amt: string, by: string) =>
			`${amt} USDC ready — claim by ${by}.`,
		claimCta: "CLAIM IT ON MY POLICIES ★",
		claimExpired: "Claim window shut — the payout returned to the pool.",
		claimNone: "On time — nothing to claim. The premium stays with the house.",
		claimAggregate: (c: number, n: number) =>
			`${c} of ${n} slip${n === 1 ? "" : "s"} claimed so far.`,
		viewTx: (explorer: string) => `TX ON ${explorer} ↗`,
		share: "SHARE ✈",
		linkCopied: "Link copied to clipboard",
		copyFailed: "Copy failed — try again",
		shareTitle: "FLIGHTS.FUN — POLICY RECORD",
		shareTextPaid: (f: string, amt: string) =>
			`My flight ${f} was late — the contract paid me ${amt} USDC. Receipts on-chain ✈`,
		shareTextReady: (f: string, amt: string) =>
			`My flight ${f} was late — ${amt} USDC payout waiting on-chain ✈`,
		shareTextGeneric: (f: string) =>
			`Flight ${f} cover on FLIGHTS.FUN — the whole lifecycle is on-chain ✈`,
	},
	keepers: {
		heroLine1: "RUN THE ROBOTS.",
		heroLine2: "KEEP THE GAME HONEST.",
		sub: "Keepers are the anyone-can-run tier of the protocol: bots that move no new information on-chain, only execute what the oracle already attested. No permission needed to read the code — and for TTL upkeep, none to run it either.",
		liveTitle: "LIVE WORKLOAD",
		liveSub:
			"What the keeper fleet is chewing on right now — read from chain, refreshed every 30s.",
		statPending: "PENDING SETTLEMENTS",
		statActive: "INSURED FLIGHTS LIVE",
		statDeposits: "QUEUED DEPOSITS",
		statWithdrawals: "QUEUED CASH-OUTS",
		tiersTitle: "WHAT KEEPERS DO",
		tierKeepers: "KEEPERS — YOU (YES, YOU)",
		tierKeepersBody:
			"classifier · settler · queue_maintainer · ttl_extender. They execute what's already attested: classify flights, drain settlements, run the LP queues, keep storage alive. The decentralization target.",
		runTitle: "RUN A KEEPER YOURSELF",
		runSub:
			"Plain TypeScript. Node 20+, a Stellar RPC URL and a funded key — laptop, server, CI, whatever stays awake.",
		runPermissionless:
			"ttl_extender IS PERMISSIONLESS TODAY — any funded key can run TTL upkeep + pruning right now.",
		runGated:
			"classifier / settler / queue_maintainer still check for the registered keeper key (spam control, not integrity — classification is deterministic from attested oracle data). An unauthorized run fails the auth check with zero side effects.",
		sourceCta: "READ THE KEEPER CODE ↗",
	},
	calc: {
		title: "UNDERWRITER CALCULATOR",
		titleHead: "UNDERWRITER",
		titleTail: "CALCULATOR",
		back: "◄ BACK TO EARN YIELD",
		intro: "Drag the levers. See what the pool clears in a month, and where the break-even line sits.",
		levers: "THE LEVERS",
		leverTravelers: "TRAVELERS BUYING / MONTH",
		leverOnTime: "% OF FLIGHTS ON TIME",
		leverPremium: "PREMIUM PER POLICY",
		leverPayout: "PAYOUT IF DELAYED",
		readout: "POOL READOUT — PER MONTH",
		premiumsCollected: "PREMIUMS COLLECTED",
		expectedPayouts: "EXPECTED PAYOUTS",
		netForPool: "NET FOR THE POOL",
		netProfit: "the pool keeps the difference: that's the yield.",
		netLoss: "at these terms the pool bleeds. Turn the levers.",
		breakEvenMeter: "BREAK-EVEN METER",
		breakEvenLabel: (pct: string) => `BREAK-EVEN: ${pct}% ON-TIME`,
		clearIt: "▲ YOU CLEAR IT",
		underIt: "▼ YOU'RE UNDER IT",
		avgNote: "US domestic average is ≈80%. Price accordingly.",
		disclaimer: "Simplified expected-value model. Not a promise of yield.",
	},
	globe: {
		titleHead: "FLIGHTS",
		titleTail: "IN THE AIR",
		intro:
			"The insured flights the system is TRACKING right now — live in the air, watched to see if they land late. Drag to spin, scroll or +/− to zoom.",
		hint: (n: number) =>
			`TRACKING · ${n} FLIGHT${n === 1 ? "" : "S"} · LIVE`,
		mapNote: (shown: number, total: number) =>
			`Showing the first ${shown} of ${total} tracked flights on the map.`,
		listTitle: "TRACKING NOW",
		searchPlaceholder: "Flight or airport… (AA100, JFK)",
		detailTitle: "SELECTED FLIGHT",
		detailEmpty: "PICK A FLIGHT",
		detailEmptySub: "Tap a node on the map or a row on the left.",
		route: "ROUTE",
		terms: "TERMS",
		delayThreshold: (h: number) => `pays if >${h}h late`,
		premiumLabel: "PREMIUM",
		payoutLabel: "PAYOUT IF DELAYED",
		riskLabel: "DELAY RISK (EST.)",
		insureCta: "INSURE ON BOARD ↗",
		legendTitle: "DELAY RISK",
		legendLow: "LOW",
		legendMed: "MED",
		legendHigh: "HIGH",
		statusInAir: "IN AIR",
		statusCancelled: "CANCELLED",
		riskNote:
			"Risk % is a deterministic ESTIMATE — no live route history on testnet.",
		demoNote:
			"DEMO tracking — no live flights on-chain right now.",
	},
	quant: {
		back: "◄ BACK TO EARN YIELD",
		titleHead: "MONTE CARLO",
		titleTail: "SIMULATOR",
		intro:
			"Same levers as the calculator — now run thousands of random months. Each trial samples how many flights land late, then tallies the pool's net. The spread is the risk.",
		levers: "THE LEVERS",
		leverTravelers: "TRAVELERS BUYING / MONTH",
		leverOnTime: "% OF FLIGHTS ON TIME",
		leverPremium: "PREMIUM PER POLICY",
		leverPayout: "PAYOUT IF DELAYED",
		leverRuns: "MONTE CARLO TRIALS",
		distTitle: "NET OUTCOME DISTRIBUTION",
		distSub: (n: number) => `${n.toLocaleString()} simulated months`,
		breakEvenTick: "BREAK-EVEN",
		statMedian: "MEDIAN NET",
		statMean: "EXPECTED (MEAN)",
		statVar: "VALUE AT RISK (5%)",
		statProfit: "P(PROFIT)",
		statMeanNote: "average across all trials",
		statVarNote: "5% of months come in below this",
		statProfitNote: "share of months the pool clears",
		leverCapital: "VAULT CAPITAL",
		leverUncertainty: "DELAY % UNCERTAINTY",
		statYield: "MEAN YIELD ON CAPITAL",
		statYieldNote: "mean net / vault capital",
		statP95: "95TH PERCENTILE",
		statP95Note: "best 5% of months clear this",
		deterministicHead: "DETERMINISTIC READOUT",
		premiumsCollected: "PREMIUMS COLLECTED",
		expectedPayouts: "EXPECTED PAYOUTS",
		netForPool: "NET FOR THE POOL",
		breakEvenLabel: (pct: string) => `BREAK-EVEN: ${pct}% ON-TIME`,
		avgNote:
			"At 80% on-time / $50 premium / $400 payout the pool bleeds — the histogram sits left of zero. Turn the levers.",
		disclaimer: "Simplified Monte Carlo model. Not a promise of yield.",
	},
	notify: {
		mintSuccess: "+10,000 USDC minted to your wallet",
		mintFailed: "Mint failed — try again",
		covered: (id: string, date: string) =>
			`Covered: ${id} on ${date} — pays if delayed`,
		depositQueued: "Deposit queued — shares mint at the next pool pass",
		depositCancelled: "Deposit request cancelled",
		withdrawQueued: "Cash-out queued",
		withdrawCancelled: "Cash-out request cancelled",
		collected: "Cash-out collected",
		claimed: (id: string) => `Payout claimed for flight ${id}!`,
	},
	info: {
		title: "HOW THIS WORKS",
		aria: "What is this?",
		docsCta: "READ THE PILOT'S MANUAL ↗",
	},
	tour: {
		welcomeTitle: "FIRST TIME HERE?",
		welcomeBody:
			"Take a quick lap around the terminal.",
		start: "SHOW ME AROUND",
		dismiss: "NO THANKS",
		skipAria: "Close the tour",
		stepLabel: (i: number, n: number) => `STEP ${i}/${n}`,
		back: "◀ BACK",
		next: "NEXT ▶",
		done: "FINISH ★",
		walletLink: "GET A WALLET ↗",
		stellarLink: "WHAT'S STELLAR? ↗",
		loading: "LOADING…",
		steps: {
			nav: {
				title: "THE COCKPIT",
				body: "Connect your Stellar wallet up top to play, and flip the site's look. New to wallets? Start here:",
			},
			board: {
				title: "THE DEPARTURES BOARD",
				body: "Search or sort the open flights, then hit INSURE on yours: pay a fixed premium, get paid automatically if it lands late.",
			},
			live: {
				title: "LIVE IN THE AIR",
				body: "Insured flights live on the globe.",
			},
			policies: {
				title: "YOUR SLIPS",
				body: "Your active cover lives here: flights in the air, payouts to claim, and settled history.",
			},
			house: {
				title: "BE THE HOUSE",
				body: "Take the other side — deposit USDC to underwrite flights and earn a cut of every premium.",
			},
			calc: {
				title: "RUN THE NUMBERS",
				body: "Estimate underwriter earnings in simulation mode — thousands of Monte Carlo months, spread and risk included.",
			},
		},
	},
	footer: {
		// rendered after the linked "Soroban testnet" prefix — see SiteFooter
		left: "same contracts, different game.",
		right: "NOT FINANCIAL ADVICE. IT'S INSURANCE, BUT FUN.",
	},
} as const

type Copy = {
	[K in keyof typeof fun]: { [P in keyof (typeof fun)[K]]: unknown }
}

const serious: Copy = {
	nav: {
		markets: "Insure",
		globe: "Live",
		policies: "Policies",
		earn: "Earn",
		settings: "Settings",
		information: "Information",
		keepers: "Keepers",
		seatbelters: "Seatbelters",
		docs: "Docs",
	},
	wallet: {
		connect: "Connect Wallet",
		menuAria: "Wallet menu",
		copyAddress: "Copy address",
		disconnect: "Disconnect",
		copied: "Address copied to clipboard",
		copyFailed: "Copy failed — try again",
		connected: (addr: string) => `Wallet connected — ${addr}`,
		disconnected: (addr: string) => `Wallet disconnected — ${addr}`,
		mismatchBanner: (net: string) =>
			`Your wallet is on a different network than this app (${net}). Switch your wallet to ${net} before signing.`,
	},
	brand: {
		name: "Flights.Fun",
		tagline: "Parametric flight delay insurance on Stellar.",
	},
	markets: {
		heroLine1: "Flight Delay",
		heroLine2: "Insurance.",
		heroSub:
			"Pay a small premium. If your flight is delayed past the threshold, receive a fixed payout in USDC — no claim forms, settled automatically on-chain.",
		heroCtaBoard: "Browse insurable flights",
		boardTitle: "Insurable Flights",
		boardHint: "Premium in → payout if delayed",
		colStake: "Premium → Payout",
		searchPlaceholder: "Search flight or airport (AA100, JFK)",
		searchAria: "Search flights by number or airport code",
		flightCount: (n: number) => `${n} flight${n === 1 ? "" : "s"}`,
		scanning: "Scanning chain",
		colFlight: "Flight",
		colRoute: "Route",
		colTrigger: "Trigger",
		colStatus: "Status",
		triggerCell: (h: number) => `Delayed over ${h}h`,
		triggerTitle: (h: number) =>
			`Pays out once the flight is more than ${h}h late, or cancelled`,
		statusScanning: "Scanning",
		statusDemo: "Sample",
		statusRecent: "Recent",
		statusBoarding: "Open",
		noMatch: (q: string) => `No flights match “${q}”`,
		noMatchHint: "Try a flight number or an airport code.",
		insureBtn: (odds: number) => `Buy Coverage · ${odds}×`,
		insureTitle: (odds: number) =>
			`Buy coverage — pays ${odds}× the premium if this flight is delayed`,
		stakeTitle: (premium: string, payout: string) =>
			`Pay a ${premium} USDC premium — receive ${payout} USDC if the flight is delayed`,
		yieldBtn: "Earn Yield",
		yieldTitle: "Take the other side — underwrite flights from the vault",
		pageLabel: (page: number, total: number, count: number) =>
			`Page ${page} of ${total} · ${count} flight${count === 1 ? "" : "s"}`,
		pagePrev: "Previous",
		pageNext: "Next",
		pageOf: (page: number, total: number) => `Page ${page} / ${total}`,
		perPage: "Per page",
		perPageAria: "Flights per page",
		sortAria: (col: string) => `Sort by ${col}`,
		flightLinkTitle: (id: string) =>
			`Track ${id} on Flightradar24 (opens in a new tab)`,
		yieldExplain:
			"takes the other side: it routes you to the underwriter vault, where premiums on on-time flights become your yield.",
		yieldExplainLead: "Earn Yield",
		demoNote:
			"Sample rows — no routes are whitelisted on-chain yet.",
	},
	statsTicker: {
		tag: "Live",
		tvl: "TVL",
		free: "Free capital",
		premiums: "Premiums",
		policiesSold: "Policies sold",
		openMarkets: "Open markets",
		insurancesPaid: "Insurances paid",
		delayed: "Delayed",
		cancelled: "Cancelled",
		paidOut: "Total paid out",
		unavailable: "Not available right now",
	},
	slip: {
		title: "Coverage",
		eyebrow: "Policy",
		closeAria: "Close coverage panel",
		oddsLabel: (odds: string) => `Pays ${odds} if delayed`,
		triggerLabel: "Delay trigger",
		dateLabel: "Flight date (UTC)",
		datePlaceholder: "Select a date",
		departsLabel: "Departure",
		departsApprox: (date: string, hm: string, iata: string) =>
			`${date} · ≈${hm} ${iata}`,
		utcShiftNote: (date: string) =>
			`Dates here are UTC — this policy covers the flight dated ${date} on your boarding pass (local time).`,
		calPrevAria: "Previous month",
		calNextAria: "Next month",
		calCloseAria: "Close calendar",
		premiumLabel: "Premium (fixed)",
		walletLabel: "Wallet USDC",
		insufficientPrompt:
			"Not enough USDC for this premium — top up your wallet first.",
		payoutLabel: "Payout if delayed",
		cta: (amt: string) => `Buy Coverage · ${amt} USDC`,
		pickDateHint: "Pick a flight date first.",
		connectPrompt: "Connect your wallet to buy this coverage.",
		blockedPrompt: "Coverage is currently limited to approved buyers.",
		unavailablePrompt: "This route is no longer available.",
		fineprint:
			"Your premium is a fixed stake on the flight being delayed. An oracle settles the flight on-chain after it lands, so the payout is automatic, with no claim forms.",
	},
	agreement: {
		eyebrow: "Notice",
		title: "Before you use this dapp",
		intro: "Please read these and confirm your eligibility before using the dapp. The full documents:",
		privacyLink: "Privacy Policy",
		termsLink: "Terms of Service",
		disclaimersLink: "Disclaimers",
		sections: [
			{
				heading: "The service",
				body: "This application is an interface to open-source parametric flight-delay insurance contracts deployed on the Stellar network. The interface operator does not custody user funds, does not act as your counterparty, and does not execute transactions on your behalf; every transaction is built and signed by your own wallet.",
			},
			{
				heading: "Eligibility",
				body: "You may not use this application if you are a resident of, or accessing it from, a prohibited or sanctioned jurisdiction, or if you are otherwise barred from using it under applicable law. It is your responsibility to confirm that using it is lawful where you are.",
			},
			{
				heading: "Risk disclosure",
				body: "Using on-chain protocols involves substantial risk of loss, up to the total loss of any funds you commit. Smart contracts may contain bugs, flight data and oracles can be late or wrong, and confirmed transactions cannot be reversed. You alone are responsible for your decisions.",
			},
			{
				heading: "No advice",
				body: "Nothing in this application constitutes financial, investment, legal, tax, accounting, or insurance advice.",
			},
			{
				heading: "Changes",
				body: "These terms may change as the protocol evolves; continued use after a change constitutes acceptance of the updated terms.",
			},
		],
		representation:
			"By pressing “Got it”, I confirm that I have read the notices above, that I am not a resident of, and am not accessing this application from, a prohibited or sanctioned jurisdiction, and that I am legally permitted to use it.",
		draftNote:
			"This summary is provided for convenience and is not the final legal language. Questions or concerns? Open an issue on",
		issuesLink: "GitHub",
		accept: "Got it",
	},
	seatbelters: {
		title: "Seatbelters",
		sub: "Those who know how to play it safe.",
		windowLabel: "Window",
		windowAria: "Leaderboard time window",
		window24h: "24h",
		window7d: "7 days",
		window30d: "30 days",
		windowAll: "All time",
		colRank: "Seat",
		colWho: "Who",
		colPolicies: "Policies",
		colPremium: "Premiums",
		colWins: "Wins",
		colPnl: "P&L",
		rankTitle: "Seats are ranked by net P&L — payouts collected minus premiums paid.",
		winsTitle: "Covered flights that settled delayed or cancelled — the ones that paid.",
		pnlTitle: "Payouts collected minus premiums paid. Seats are ranked by this.",
		loading: "Loading",
		loadError: "The board is unavailable — try again in a moment.",
		empty: "No seatbelters yet. Buckle up first, brag forever.",
		emptyWindow: "Quiet skies — no cover bought in this window.",
		emptyCta: "Browse flights",
		seatsOpen: (n: number) =>
			`${n} seat${n === 1 ? "" : "s"} still open on this list.`,
		explorerTitle: (label: string) => `View account on ${label} ↗`,
		youTitle: "Your seat",
		you: "You",
		youConnect: "Connect your wallet to find your seat.",
		youOffBoard: "No cover bought in this window → no seat yet.",
		youError: "Your seat is unavailable right now.",
		fineprint:
			"Testnet numbers — test USDC has no monetary value. Seats rank by net P&L over policies seen by the chain-event mirror.",
	},
	house: {
		heroLine1: "Underwriter",
		heroLine2: "Vault.",
		sub: "Deposit USDC to back flight-delay policies and earn a share of every premium. On-time flights pay yield; delayed flights draw on the pool.",
		statTvl: "Total Value Locked",
		statBacking: "Backing Policies",
		statFree: "Free Capital",
		statApr: "Realized APR (90d)",
		aprHover: (apy: string, days: number) =>
			`${apy}% APY (compounded) · measured over ${days}d of recorded vault history`,
		aprInfo:
			"What the vault actually earned, annualized — not a promised rate. Underwriters collect the premium on every policy and fund the payout on every delayed or cancelled flight; the net accrues to the share price, so the share price is the only input. We read it at the two ends of a 90-day window and annualize: APR = (end ÷ start − 1) × 365 ÷ days. Hover the number for the APY, which compounds the same move instead: APY = (end ÷ start) ^ (365 ÷ days) − 1. That compounding is the only difference between them — identical data, so APY always reads higher, and dramatically higher over a short window. The window is fixed at 90 days deliberately: annualizing a few days turns a single settlement into a headline (this vault showed +357% APY, then a dash, then −55% APY within four days while its share price moved a total of +1.0%). Both are backward-looking, and a dash means too little recorded history to measure. The window only reaches back as far as the vault's recorded history goes — hover shows how many days were actually measured.",
		deposit: "Deposit",
		depositAmount: "Amount (USDC)",
		walletBalance: "Wallet balance:",
		walletHint: "· mint test USDC from the top bar.",
		bridgeLink: "Bridge USDC (for mainnet)",
		depositCta: "Deposit — Earn Yield",
		depositQueueHint:
			"Deposits queue for a ~6-hour safety delay, then shares mint to your wallet automatically — at the share price when processed, not when queued.",
		depositQueued: (amt: string) => `${amt} USDC queued`,
		maxBtn: "Max",
		insufficientBalance: "That's more USDC than your wallet holds.",
		connectWallet: "Connect Wallet",
		position: "Your Position",
		poolShares: "Vault Shares",
		currentValue: "Current Value",
		premiumsEarned: "Premiums Earned (all time)",
		cashOut: "Withdraw",
		cashOutAmount: "Amount (shares)",
		insufficient: "That's more shares than you hold.",
		queueCta: "Queue Withdrawal",
		queueHint:
			"Withdrawals unlock after a ~6-hour safety delay, then pay out as the vault frees capital — collect below when ready.",
		withdrawPreview: (amt: string) => `≈ ${amt} USDC at the current share price`,
		yourQueue: "Your Queue",
		queueEmpty: "No queued withdrawals",
		queuePosition: (n: number) => `#${n} in line`,
		queueShares: (amt: string) => `${amt} shares`,
		queueEta: (when: string) => `Unlocks in ~${when}`,
		queueReady: "Ready — awaiting the next processing pass",
		cancel: "Cancel",
		readyToCollect: "Ready to Collect",
		collectCta: "Collect",
		nothingToCollect: "Nothing to collect yet",
		fineprint:
			"The vault is a Soroban vault: deposits mint shares, premiums accrue to the share price, and payouts on delayed flights are absorbed by the vault. Deposits and withdrawals are both processed after a ~6-hour safety delay, at the share price current at processing time. Underwriting carries risk.",
		calcCta: "How much can you earn? Run the numbers →",
		calcCtaHead: "How much can you earn?",
		calcCtaTail: "Run the numbers →",
		utilWarn:
			"Vault is fully utilized — withdrawals will queue until capital frees up.",
		queueRail: "Withdrawal Queue",
		queueRailEmpty: "No withdrawals queued.",
		queueMine: "You",
		sharePriceTitle: "Share Price",
		sharePriceSub: (n: number) => `Last ${n} days`,
		realizedYield: (period: string, days: number, apr: string, apy: string) =>
			`Realized ${period}% over ${days} day${days === 1 ? "" : "s"} ≈ ${apr}% APR · ${apy}% APY`,
		illustrative: "Illustrative",
		statsUnavailable:
			"Some pool numbers didn't load — retrying automatically.",
		sparkTvl: "TVL trend",
		sparkApy: "APY trend",
	},
	policies: {
		title: "My Policies",
		connectPrompt: "Connect your wallet to view your policies (top right).",
		connectSub:
			"Connect your wallet to see your active coverage, payouts to claim, and settled policies.",
		intro:
			"Your active coverage in the air, payouts to claim, and settled history.",
		loading: "Loading your policies…",
		loadError: "Couldn't load your policies — the network didn't respond.",
		loadErrorSub:
			"Your policies are safe on-chain; this page just couldn't read them right now.",
		retry: "Retry",
		liveScheduled: "Scheduled",
		liveInAir: "In air",
		liveLanded: "Landed",
		liveCancelled: "Cancelled",
		liveDelayedSettling: "Delayed — settling",
		liveOnTimeSettling: "On time — settling",
		outcomeOnTime: "On time — no payout",
		outcomeDelayedPays: "Delayed — payout ready",
		outcomeCancelledPays: "Cancelled — payout ready",
		outcomeDelayedPaid: "Delayed — paid",
		outcomeCancelledPaid: "Cancelled — paid",
		outcomeDelayedExpired: "Delayed — claim expired",
		outcomeCancelledExpired: "Cancelled — claim expired",
		empty: "No policies yet",
		emptyCta: "Browse flights →",
		total: (n: number) => `${n} polic${n === 1 ? "y" : "ies"} on record`,
		active: "Active",
		activeSub: "Live coverage. These flights are being tracked.",
		claim: "Ready to Claim",
		claimSub: "Delayed or cancelled. Claim before the window closes.",
		claimWin: "Delayed — payout ready",
		claimBtn: "Claim Payout",
		claiming: "Claiming…",
		payoutLabel: "Payout",
		history: "History — Settled",
		historySub: "Closed policies, with the reason each is terminal.",
		historyFilterLabel: "Show",
		historyFilterAria: "Hide settled policies older than",
		historyFilterAll: "All",
		historyFilterDays: (d: number) => `Last ${d} days`,
		historyStatusLabel: "Status",
		historyStatusAria: "Show only settled policies with this status",
		historyHidden: (n: number) => `${n} hidden by filters`,
		badgeTracking: "Tracking",
		badgeOnTime: "On time",
		badgeClaimable: "Payout ready",
		badgePaid: "Paid out",
		badgeExpired: "Window closed",
		reasonPaid: "Paid out — payout claimed.",
		reasonOnTime: "On time — no payout.",
		reasonExpired: "Claim window expired — unclaimed.",
		reasonDelayedPaid: "Delayed — paid out.",
		reasonCancelledPaid: "Cancelled — paid out.",
		claimWindow: (d: string) => `Claim by ${d}`,
		expiresIn: (left: string) => `Expires in ${left}`,
		expiresNow: "Window closing — claim now",
		remindBtn: "🔔 Remind me",
		remindBtnTitle:
			"Get a browser notification when a payout is close to expiring",
		remindOn:
			"Reminders on — you'll get a heads-up when a payout nears expiry.",
		notifTitle: (amt: string) => `${amt} USDC payout waiting`,
		notifBody: (flight: string, left: string) =>
			`${flight}: claim before the window shuts — ${left} left.`,
		depTime: (hm: string) => `Dep ${hm}`,
	},
	alerts: {
		promptTitle: "Stay in the loop?",
		promptBody:
			"Get a browser alert when your flight is delayed, a payout is ready, or your vault deposit is processed. Works while a tab with this app is open.",
		promptEnable: "Enable alerts",
		promptDismiss: "Not now",
		promptNever: "Never",
		enabledToast:
			"Alerts on — you'll get a heads-up when something needs you.",
		delayed: (f: string) => `${f} is delayed`,
		delayedBody: "Your covered flight hit the threshold — a payout is on the way.",
		cancelledFlight: (f: string) => `${f} was cancelled`,
		cancelledBody: "Your covered flight was cancelled — a payout is on the way.",
		settledOnTime: (f: string) => `${f} landed on time`,
		settledOnTimeBody: "Policy settled — no payout this trip.",
		payoutReady: (amt: string) => `Payout ready: ${amt} USDC`,
		payoutReadyBody: (f: string) =>
			`${f} settled in your favor. Claim before the window closes.`,
		depositProcessed: "Vault deposit processed",
		depositProcessedBody: "Your shares are minted and earning.",
		withdrawalProcessed: "Vault withdrawal processed",
		withdrawalProcessedBody: "Your USDC is ready to collect on the Earn page.",
	},
	policyDetail: {
		eyebrow: "Policy record",
		detailsLink: "Details →",
		back: "← My Policies",
		loading: "Loading the record…",
		loadError: "Couldn't read the chain.",
		loadErrorSub:
			"The record is safe on-chain; this page just couldn't read it right now.",
		retry: "Retry",
		notFound: "No record for this flight",
		notFoundSub:
			"Nothing on-chain for this flight and date. Check the link, or browse insurable flights.",
		notFoundCta: "Browse flights →",
		dateLabel: "Flight date (UTC)",
		premiumLabel: "Premium",
		payoutLabel: "Payout if delayed",
		triggerLabel: (h: number) =>
			`Trigger: delayed over ${h}h, or cancelled`,
		buyers: (n: number) => `${n} polic${n === 1 ? "y" : "ies"} sold`,
		claimedOf: (c: number, n: number) => `${c}/${n} claimed`,
		viewingAs: (addr: string) => `Policy held by ${addr}`,
		noPolicyForWallet:
			"This wallet holds no policy on this flight — showing the flight's public record.",
		timelineTitle: "Lifecycle",
		timelineSub:
			"Each step below is a public on-chain fact you can verify independently.",
		stepSaleTitle: "Sale window",
		stepSaleOpen: (d: string) =>
			`Open — coverage on sale until ${d}.`,
		stepSaleDone:
			"The flight was verified against the live schedule, then sales closed before departure.",
		stepSaleNone: "No sale window on record for this flight and date.",
		stepBuyTitle: "Coverage purchased",
		stepBuyKnown: (premium: string) =>
			`A ${premium} USDC premium was paid. The policy is recorded on-chain.`,
		stepBuyMarket: (n: number) =>
			`${n} traveler${n === 1 ? "" : "s"} purchased this coverage.`,
		stepBuyNone: "No policies were sold on this flight.",
		boughtAt: (when: string) => `Purchased ${when}`,
		stepEtaTitle: "Schedule attested",
		stepEtaDone: (when: string) =>
			`The oracle recorded the published timetable: scheduled arrival ${when}. Every payout decision is measured from this baseline.`,
		stepEtaPending:
			"The oracle records the published timetable when tracking starts.",
		stepOutcomeTitle: "Flight outcome",
		stepOutcomeLanded: (when: string) => `Landed ${when}.`,
		stepOutcomeLate: (dur: string) =>
			`That is ${dur} past the scheduled arrival.`,
		stepOutcomeNotLate: "At (or before) the scheduled arrival.",
		stepOutcomeCancelled:
			"Cancelled — corroborated by the oracle before being recorded on-chain.",
		stepOutcomePending: "Pending — the flight hasn't landed yet.",
		stepSettleTitle: "Settled on-chain",
		settleMathLate: (late: string, h: number) =>
			`${late} late against the ${h}h threshold → classified Delayed. The contract pays.`,
		settleMathOnTime: (late: string, h: number) =>
			`${late} late against the ${h}h threshold → classified On time. No payout.`,
		settleCancelled: "Cancelled → the contract pays the full payout.",
		stepSettlePending:
			"Awaiting the automated settlement sweep — no claim forms involved.",
		settledAt: (when: string) => `Settled ${when}`,
		stepClaimTitle: "Payout",
		claimPaid: (amt: string) =>
			`${amt} USDC claimed and transferred to the wallet.`,
		claimReady: (amt: string, by: string) =>
			`${amt} USDC available — claim by ${by}.`,
		claimCta: "Claim it on My Policies →",
		claimExpired:
			"The claim window closed — the payout returned to the pool.",
		claimNone:
			"On time — no payout due. The premium remains with the underwriting pool.",
		claimAggregate: (c: number, n: number) =>
			`${c} of ${n} polic${n === 1 ? "y" : "ies"} claimed so far.`,
		viewTx: (explorer: string) => `Transaction on ${explorer} ↗`,
		share: "Share",
		linkCopied: "Link copied to clipboard",
		copyFailed: "Copy failed — try again",
		shareTitle: "Flights.Fun — policy record",
		shareTextPaid: (f: string, amt: string) =>
			`Flight ${f} was delayed — the contract paid out ${amt} USDC, verifiable on-chain.`,
		shareTextReady: (f: string, amt: string) =>
			`Flight ${f} was delayed — a ${amt} USDC payout is waiting on-chain.`,
		shareTextGeneric: (f: string) =>
			`Flight ${f} coverage on Flights.Fun — the full policy lifecycle, on-chain.`,
	},
	keepers: {
		heroLine1: "Keeper bots.",
		heroLine2: "The anyone-can-run tier.",
		sub: "Keepers are the protocol's permissionless operations tier: bots that move no new information on-chain, only execute what the oracle has already attested. The code is open source — and for TTL upkeep, running it requires no authorization at all.",
		liveTitle: "Live workload",
		liveSub:
			"What the keeper fleet is processing right now.",
		statPending: "Pending settlements",
		statActive: "Insured flights live",
		statDeposits: "Queued deposits",
		statWithdrawals: "Queued withdrawals",
		tiersTitle: "What keepers do",
		tierKeepers: "Keepers — open to anyone",
		tierKeepersBody:
			"classifier · settler · queue_maintainer · ttl_extender. They execute what's already attested: classify flights, drain settlements, process the LP queues, keep contract storage alive. This tier is the decentralization target.",
		runTitle: "Run a keeper yourself",
		runSub:
			"Plain TypeScript. Node 20+, a Stellar RPC URL and a funded key — a laptop, server, or CI job all work.",
		runPermissionless:
			"ttl_extender is permissionless today — any funded key can run TTL upkeep and pruning right now.",
		runGated:
			"classifier / settler / queue_maintainer still require the registered keeper key (spam control, not integrity — classification is deterministic from attested oracle data). An unauthorized run fails the on-chain auth check with no side effects.",
		sourceCta: "Read the keeper code ↗",
	},
	calc: {
		title: "Underwriter Calculator",
		titleHead: "Underwriter",
		titleTail: "Calculator",
		back: "← Back to Earn Yield",
		intro: "Adjust the assumptions to see the pool's expected monthly result and where break-even sits.",
		levers: "Assumptions",
		leverTravelers: "Travelers buying / month",
		leverOnTime: "% of flights on time",
		leverPremium: "Premium per policy",
		leverPayout: "Payout if delayed",
		readout: "Projected result — per month",
		premiumsCollected: "Premiums collected",
		expectedPayouts: "Expected payouts",
		netForPool: "Net for the vault",
		netProfit: "The vault keeps the difference. That's the yield.",
		netLoss: "At these terms the vault runs a loss. Adjust the assumptions.",
		breakEvenMeter: "Break-even meter",
		breakEvenLabel: (pct: string) => `Break-even: ${pct}% on-time`,
		clearIt: "You clear it",
		underIt: "You're under it",
		avgNote: "US domestic average is around 80%. Price accordingly.",
		disclaimer: "Simplified expected-value model. Not a promise of yield.",
	},
	globe: {
		titleHead: "Flights",
		titleTail: "In the Air",
		intro:
			"The insured flights being tracked right now — live in the air, watched to see if they land late. Drag to rotate, scroll or +/− to zoom.",
		hint: (n: number) =>
			`Tracking · ${n} flight${n === 1 ? "" : "s"} · live`,
		mapNote: (shown: number, total: number) =>
			`Showing the first ${shown} of ${total} tracked flights on the map.`,
		listTitle: "Tracking now",
		searchPlaceholder: "Search flight or airport (AA100, JFK)",
		detailTitle: "Selected Flight",
		detailEmpty: "Select a flight",
		detailEmptySub: "Choose a node on the map or a row on the left.",
		route: "Route",
		terms: "Terms",
		delayThreshold: (h: number) => `pays if delayed over ${h}h`,
		premiumLabel: "Premium",
		payoutLabel: "Payout if delayed",
		riskLabel: "Delay risk (est.)",
		insureCta: "Buy coverage on board →",
		legendTitle: "Delay risk",
		legendLow: "Low",
		legendMed: "Med",
		legendHigh: "High",
		statusInAir: "In air",
		statusCancelled: "Cancelled",
		riskNote:
			"Risk % is a deterministic estimate — no live route history on testnet.",
		demoNote:
			"Sample tracking — no live flights on-chain yet.",
	},
	quant: {
		back: "← Back to Earn Yield",
		titleHead: "Monte Carlo",
		titleTail: "Simulator",
		intro:
			"The same assumptions as the calculator, run across thousands of random months. Each trial samples how many flights are delayed, then tallies the pool's net result. The spread is the risk.",
		levers: "Assumptions",
		leverTravelers: "Travelers buying / month",
		leverOnTime: "% of flights on time",
		leverPremium: "Premium per policy",
		leverPayout: "Payout if delayed",
		leverRuns: "Monte Carlo trials",
		distTitle: "Net outcome distribution",
		distSub: (n: number) => `${n.toLocaleString()} simulated months`,
		breakEvenTick: "Break-even",
		statMedian: "Median net",
		statMean: "Expected (mean)",
		statVar: "Value at Risk (5%)",
		statProfit: "P(profit)",
		statMeanNote: "average across all trials",
		statVarNote: "5% of months fall below this",
		statProfitNote: "share of months the pool clears",
		leverCapital: "Vault capital",
		leverUncertainty: "Delay % uncertainty",
		statYield: "Mean yield on capital",
		statYieldNote: "mean net / vault capital",
		statP95: "95th percentile",
		statP95Note: "best 5% of months clear this",
		deterministicHead: "Deterministic readout",
		premiumsCollected: "Premiums collected",
		expectedPayouts: "Expected payouts",
		netForPool: "Net for the vault",
		breakEvenLabel: (pct: string) => `Break-even: ${pct}% on-time`,
		avgNote:
			"At 80% on-time / $50 premium / $400 payout the pool runs a loss — the distribution sits left of zero. Adjust the assumptions.",
		disclaimer: "Simplified Monte Carlo model. Not a promise of yield.",
	},
	notify: {
		mintSuccess: "+10,000 USDC minted to your wallet",
		mintFailed: "Mint failed — try again",
		covered: (id: string, date: string) =>
			`Coverage purchased: ${id} on ${date} — pays if delayed`,
		depositQueued: "Deposit queued — shares mint at the next pool pass",
		depositCancelled: "Deposit request cancelled",
		withdrawQueued: "Withdrawal queued",
		withdrawCancelled: "Withdrawal request cancelled",
		collected: "Withdrawal collected",
		claimed: (id: string) => `Payout claimed for flight ${id}.`,
	},
	info: {
		title: "How this works",
		aria: "What is this?",
		docsCta: "Read the docs →",
	},
	tour: {
		welcomeTitle: "FIRST TIME HERE?",
		welcomeBody:
			"Take a short tour of the app.",
		start: "Show me around",
		dismiss: "No thanks",
		skipAria: "Close the tour",
		stepLabel: (i: number, n: number) => `Step ${i} of ${n}`,
		back: "← Back",
		next: "Next →",
		done: "Finish",
		walletLink: "Create a wallet →",
		stellarLink: "Learn about Stellar →",
		loading: "Loading…",
		steps: {
			nav: {
				title: "The top bar",
				body: "Connect your Stellar wallet here and adjust the site's appearance. New to wallets? Start here:",
			},
			board: {
				title: "Insurable flights",
				body: "Search or sort the open flights, then pick one and buy coverage: pay a fixed premium, receive an automatic payout if it's delayed.",
			},
			live: {
				title: "Live flights",
				body: "Insured flights live on the globe.",
			},
			policies: {
				title: "My Policies",
				body: "Your active coverage: flights in the air, payouts to claim, and settled history.",
			},
			house: {
				title: "Underwriter vault",
				body: "Take the other side — deposit USDC to back policies and earn a share of every premium.",
			},
			calc: {
				title: "Run the numbers",
				body: "Estimate underwriter earnings in simulation mode — a Monte Carlo run over thousands of months, spread and risk included.",
			},
		},
	},
	footer: {
		left: "parametric flight delay insurance.",
		right: "Not financial advice.",
	},
}

export function useCopy(): typeof fun {
	const { theme } = useTheme()
	// serious mirrors the fun shape (enforced by the Copy type); the cast
	// hands callers the fun map's precise types (incl. the fn signatures).
	return (theme === "serious" ? serious : fun) as typeof fun
}
