[package]
name = "flight_pool"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
recovery_pool = { path = "../recovery_pool" }
risk_vault = { path = "../risk_vault" }

[package.metadata.stellar]
cargo_inherit = true
