[package]
name = "controller"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
stellar-access = { workspace = true }
stellar-macros = { workspace = true }
stellar-contract-utils = { workspace = true }
sentinel_types = { path = "../sentinel_types" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
governance_module = { path = "../governance_module" }
risk_vault = { path = "../risk_vault" }
oracle_aggregator = { path = "../oracle_aggregator" }
flight_pool_manager = { path = "../flight_pool_manager" }

[package.metadata.stellar]
cargo_inherit = true

[lints]
workspace = true
