[workspace]
resolver = "2"
members = [
    "sentinel_types",
    "mock_usdc",
    "governance_module",
    "risk_vault",
    "oracle_aggregator",
    "flight_pool_manager",
    "controller",
    "integration_tests",
]
exclude = ["target", "risk_vault/fuzz", "oracle_aggregator/fuzz"]

[workspace.dependencies]
soroban-sdk = "25.3.1"
stellar-tokens = "0.7.1"
stellar-access = "0.7.1"
stellar-macros = "0.7.1"
stellar-contract-utils = "0.7.1"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
